# Generated by Django 3.2.11 on 2023-02-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_base_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp',
            new_name='Employee',
        ),
    ]
