# Generated by Django 3.2.19 on 2023-06-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='bloog_group',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='employeedetail',
            old_name='whatspp_number',
            new_name='whatsapp_number',
        ),
    ]
